name: Sync
on:
  push:
    branches:
      - main

jobs:
  branches-sync:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Opening pull request
        id: pull
        uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
